#
# This docker compose file is for DEVELOPMENT and TESTING purposes ONLY it is not suitable for production use
# It does however let you run the app in production mode if you want to test that
#
# If you need to leave the container running for example to debug something you can use the following command to keep it running
# command: ["tail", "-f", "/dev/null"]
services:
  # Outpost app
  outpost:
    image: "outpost:development"
    container_name: outpost
    # entrypoint: [".docker/services/outpost/docker-entrypoint.sh"]
    # command: ["bin/dev"]
    # use if you just want to keep the container running
    # command: ["tail", "-f", "/dev/null"]
    # uncomment for 'prod' like env locally
    # command: ["bin/bundle", "exec", "puma", "-C", "config/puma.rb"]
    init: true
    depends_on:
      - postgres
      - mongo
    # platform: linux/amd64  # or linux/arm64, or omit for auto-detect
    build:
      context: .
      # uncomment for 'prod' like env locally
      # NODE_ENV: production
      # RAILS_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./:/app:cached
      - /app/node_modules
      - /app/tmp
    environment:
      # uncomment for 'prod' like env locally
      # NODE_ENV: production
      # RAILS_ENV: production
      OFSTED_FEED_API_ENDPOINT: ${OFSTED_FEED_API_ENDPOINT:-http://ofsted-stub:8000}
      SHOW_ENV_BANNER: ${SHOW_ENV_BANNER:-outpost docker development}
      DB_URI: mongodb://${MONGO_INITDB_USERNAME:-outpost}:${MONGO_INITDB_PASSWORD:-password}@mongo/${MONGO_INITDB_DATABASE:-outpost_api_development}
      DATABASE_URL: ${DATABASE_URL:-postgresql://outpost:password@postgres:5432/outpost?}
    networks:
      - external_network
      - internal_network

  outpost-api-service:
    extends:
      file: ./.docker/services/outpost-api-service/outpost-api-service.yml
      service: outpost-api-service
    depends_on:
      - mongo

  # Ofsted stub
  ofsted-stub:
    build:
      context: ./.docker/services/ofsted-stub
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: ofsted-stub
    networks:
      - internal_network
      - external_network

  # Databases

  postgres:
    extends:
      file: ./.docker/services/postgres/postgres.yml
      service: postgres
    networks:
      - external_network

  mongo:
    extends:
      file: ./.docker/services/mongo/mongo.yml
      service: mongo
    networks:
      - external_network

volumes:
  mongo-volume:
  postgres-volume:

networks:
  external_network:
  internal_network:
    internal: true
