ARG STACK_VERSION=20
ARG NODE_ENV=development
ARG RAILS_ENV=test

# ------------
# add application code to herokuish container
# build application (and install correct buildpacks from app.json along with it)
# generate slug as app.tar.gz
# ------------
FROM gliderlabs/herokuish:latest-${STACK_VERSION}
WORKDIR /tmp/app
COPY ./app.json /tmp

ARG NODE_ENV
ARG RAILS_ENV
ENV NODE_ENV=${NODE_ENV}
ENV RAILS_ENV=${RAILS_ENV}
# tmp NODE_OPTIONS for now
ENV NODE_OPTIONS=--openssl-legacy-provider 
# RUN (cat /tmp/app/app.json || echo '{}') | jq -r '.buildpacks[].url' > /tmp/app/.buildpacks && \
#   (test -s /tmp/app/.buildpacks || rm /tmp/app/.buildpacks)
RUN (cat /tmp/app.json || echo '{}') | jq -r '.environments.test.buildpacks[].url' > /tmp/app/.buildpacks && \
  (test -s /tmp/app/.buildpacks || rm /tmp/app/.buildpacks)
RUN while IFS= read -r line; do herokuish buildpack install "$line"; done < /tmp/app/.buildpacks



RUN apt-get update --error-on=any


# for chrome for tests
RUN apt-get install -y \
  gconf-service \
  libappindicator1 \
  libasound2 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcairo-gobject2 \
  libdrm2 \
  libgbm1 \
  libgconf-2-4 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libx11-xcb1 \
  libxcb-dri3-0 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxfixes3 \
  libxi6 \
  libxinerama1 \
  libxrandr2 \
  libxshmfence1 \
  libxss1 \
  libxtst6 \
  fonts-liberation \
  jq


# Fetch the latest version numbers and URLs for Chrome and ChromeDriver
RUN curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json > /tmp/versions.json

# chrome
RUN CHROME_URL=$(jq -r '.channels.Stable.downloads.chrome[] | select(.platform=="linux64") | .url' /tmp/versions.json) && \
  wget -q --continue -O /tmp/chrome-linux64.zip $CHROME_URL && \
  unzip -j /tmp/chrome-linux64.zip -d /opt/chrome

RUN chmod +x /opt/chrome/chrome

# chromedriver
RUN CHROMEDRIVER_URL=$(jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url' /tmp/versions.json) && \
  wget -q --continue -O /tmp/chromedriver-linux64.zip $CHROMEDRIVER_URL && \
  unzip -j /tmp/chromedriver-linux64.zip -d /opt/chromedriver && \
  chmod +x /opt/chromedriver/chromedriver

# Clean up
RUN rm /tmp/chrome-linux64.zip /tmp/chromedriver-linux64.zip /tmp/versions.json

ENV PATH /opt/chrome:/opt/chromedriver:$PATH
RUN echo 'export PATH="/opt/chrome:/opt/chromedriver:$PATH"' >> ~/.bashrc

# Check chrome & chromedriver versions
RUN echo "Chrome: " && chrome --version
RUN echo "Chromedriver: " && chromedriver --version

ENTRYPOINT [ "/bin/herokuish" ]
CMD [ "buildpack", "test" ]