FROM ruby:3.1.7

RUN apt-get -y update && \
apt-get -y --no-install-recommends install \
build-essential \
sudo \
curl \
git \
htop \
libjemalloc2 \
pkg-config \
jq


RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get -y --no-install-recommends install nodejs

# enable yarn
RUN corepack enable

RUN apt-get clean
RUN gem install bundler

# Create a non-root user and add to sudo group
RUN useradd -m -s /bin/bash -G sudo outpost-user

# Optionally, allow passwordless sudo for convenience (not recommended for production)
RUN echo "outpost-user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the new user
USER outpost-user

WORKDIR /app

EXPOSE 3000

CMD ["/bin/bash"]
