ARG STACK_VERSION=22
ARG NODE_ENV=test
ARG RAILS_ENV=test

# ------------
# add application code to herokuish container
# install buildpacks from test environment in app.json 
# build application 
# run /exec bin/bundle exec rspec
# ------------
FROM gliderlabs/herokuish:latest-${STACK_VERSION}
COPY . /tmp/app
COPY ./app.json /tmp

ARG NODE_ENV
ARG RAILS_ENV
ENV NODE_ENV=${NODE_ENV}
ENV RAILS_ENV=${RAILS_ENV}
# RUN (cat /tmp/app/app.json || echo '{}') | jq -r '.buildpacks[].url' > /tmp/app/.buildpacks && \
#   (test -s /tmp/app/.buildpacks || rm /tmp/app/.buildpacks)
RUN (cat /tmp/app.json || echo '{}') | jq -r '.environments.test.buildpacks[].url' > /tmp/app/.buildpacks && \
  (test -s /tmp/app/.buildpacks || rm /tmp/app/.buildpacks)
RUN while IFS= read -r line; do herokuish buildpack install "$line"; done < /tmp/app/.buildpacks

ENV BUNDLE_WITHOUT=""

RUN /build && \
  rm -Rf /tmp/* 


ENTRYPOINT [ "/exec" ]
CMD [ "bin/bundle", "exec", "rspec" ]