import "nodelist-foreach-polyfill"
import "polyfill-array-includes"

import tabs from "./tabs"
import collapsible from "./collapsible"
import filters from "./filters"
import snapshots from "./snapshots"
import maps from "./maps"
import locations from "./locations"
import intro from "./intro"
import labels from "./labels"
import choices from "./choices"