import "nodelist-foreach-polyfill"
import "polyfill-array-includes"
import "time-input-polyfill/auto"

import tabs from "./tabs"
import collapsible from "./collapsible"
import filters from "./filters"
import snapshots from "./snapshots"
import maps from "./maps"
import locations from "./locations"
import intro from "./intro"
import labels from "./labels"
import localOffer from "./local-offer"
import regularSchedule from "./regular-schedule"
import openCloseAll from "./open-close-all"
import wordCount from "./word-count"
import helpTips from "./help-tips"

import choices from "./choices"