version: "3.7"
services:
  postgres:
    image: postgres:13.7-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-outpost}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-outpost_development}
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres-volume:
