name: Deploy Images to GHCR

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: |
          docker build . --target production --tag ghcr.io/wearefuturegov/outpost:latest
          docker push ghcr.io/wearefuturegov/outpost:latest
